apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vksm35bxz-python 
  janus-idp.io/tekton: vksm35bxz-python
  backstage.io/kubernetes-id: vksm35bxz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vksm35bxz-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  