apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vksm35bxz-python
  janus-idp.io/tekton: vksm35bxz-python
  backstage.io/kubernetes-id: vksm35bxz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vksm35bxz-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
